apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadygzc6206-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadygzc6206-tenant-component
    app.kubernetes.io/part-of: loadygzc6206-tenant-app
  name: loadygzc6206-tenant-component
  namespace: loadygzc6206-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadygzc6206-tenant-component
    weight: null
status: {}
